//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIScaler) DeepCopyInto(out *AIScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIScaler.
func (in *AIScaler) DeepCopy() *AIScaler {
	if in == nil {
		return nil
	}
	out := new(AIScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIScalerList) DeepCopyInto(out *AIScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIScalerList.
func (in *AIScalerList) DeepCopy() *AIScalerList {
	if in == nil {
		return nil
	}
	out := new(AIScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIScalerSpec) DeepCopyInto(out *AIScalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.Constraints = in.Constraints
	in.LLM.DeepCopyInto(&out.LLM)
	out.Prometheus = in.Prometheus
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]SignalSourceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(AlertingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(CostConfig)
		**out = **in
	}
	if in.CostConstraints != nil {
		in, out := &in.CostConstraints, &out.CostConstraints
		*out = new(CostConstraints)
		**out = **in
	}
	if in.SLOs != nil {
		in, out := &in.SLOs, &out.SLOs
		*out = make([]SLO, len(*in))
		copy(*out, *in)
	}
	if in.SLOViolationBudget != nil {
		in, out := &in.SLOViolationBudget, &out.SLOViolationBudget
		*out = new(SLOViolationBudget)
		**out = **in
	}
	if in.VerticalScaling != nil {
		in, out := &in.VerticalScaling, &out.VerticalScaling
		*out = new(VerticalScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationProfile != nil {
		in, out := &in.ApplicationProfile, &out.ApplicationProfile
		*out = new(ApplicationProfile)
		**out = **in
	}
	if in.ResourceProfiles != nil {
		in, out := &in.ResourceProfiles, &out.ResourceProfiles
		*out = make([]ResourceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PredictiveScaling != nil {
		in, out := &in.PredictiveScaling, &out.PredictiveScaling
		*out = new(PredictiveScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Safety != nil {
		in, out := &in.Safety, &out.Safety
		*out = new(SafetyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LLMRateLimit != nil {
		in, out := &in.LLMRateLimit, &out.LLMRateLimit
		*out = new(LLMRateLimit)
		**out = **in
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = new(DependencyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KEDAIntegration != nil {
		in, out := &in.KEDAIntegration, &out.KEDAIntegration
		*out = new(KEDAIntegration)
		**out = **in
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(ApprovalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Precedence != nil {
		in, out := &in.Precedence, &out.Precedence
		*out = new(PrecedenceConfig)
		**out = **in
	}
	if in.Feedback != nil {
		in, out := &in.Feedback, &out.Feedback
		*out = new(FeedbackConfig)
		**out = **in
	}
	if in.StatefulSetPolicy != nil {
		in, out := &in.StatefulSetPolicy, &out.StatefulSetPolicy
		*out = new(StatefulSetPolicy)
		**out = **in
	}
	out.EvaluationInterval = in.EvaluationInterval
	out.CooldownPeriod = in.CooldownPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIScalerSpec.
func (in *AIScalerSpec) DeepCopy() *AIScalerSpec {
	if in == nil {
		return nil
	}
	out := new(AIScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIScalerStatus) DeepCopyInto(out *AIScalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.CurrentResources != nil {
		in, out := &in.CurrentResources, &out.CurrentResources
		*out = new(ResourceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Prediction != nil {
		in, out := &in.Prediction, &out.Prediction
		*out = new(PredictionStatus)
		**out = **in
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(CostStatus)
		**out = **in
	}
	if in.LLMTelemetry != nil {
		in, out := &in.LLMTelemetry, &out.LLMTelemetry
		*out = new(LLMTelemetry)
		**out = **in
	}
	if in.Precedence != nil {
		in, out := &in.Precedence, &out.Precedence
		*out = new(PrecedenceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Feedback != nil {
		in, out := &in.Feedback, &out.Feedback
		*out = new(FeedbackStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIScalerStatus.
func (in *AIScalerStatus) DeepCopy() *AIScalerStatus {
	if in == nil {
		return nil
	}
	out := new(AIScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOverride) DeepCopyInto(out *ActiveOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOverride.
func (in *ActiveOverride) DeepCopy() *ActiveOverride {
	if in == nil {
		return nil
	}
	out := new(ActiveOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertRule) DeepCopyInto(out *AlertRule) {
	*out = *in
	out.For = in.For
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertRule.
func (in *AlertRule) DeepCopy() *AlertRule {
	if in == nil {
		return nil
	}
	out := new(AlertRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingConfig) DeepCopyInto(out *AlertingConfig) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]AlertRule, len(*in))
		copy(*out, *in)
	}
	if in.WebhookSecret != nil {
		in, out := &in.WebhookSecret, &out.WebhookSecret
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingConfig.
func (in *AlertingConfig) DeepCopy() *AlertingConfig {
	if in == nil {
		return nil
	}
	out := new(AlertingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisConfig) DeepCopyInto(out *AnalysisConfig) {
	*out = *in
	out.Window = in.Window
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisConfig.
func (in *AnalysisConfig) DeepCopy() *AnalysisConfig {
	if in == nil {
		return nil
	}
	out := new(AnalysisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfile) DeepCopyInto(out *ApplicationProfile) {
	*out = *in
	out.ColdStartDuration = in.ColdStartDuration
	out.WarmUpDuration = in.WarmUpDuration
	out.GracefulShutdownDuration = in.GracefulShutdownDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfile.
func (in *ApplicationProfile) DeepCopy() *ApplicationProfile {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalConfig) DeepCopyInto(out *ApprovalConfig) {
	*out = *in
	if in.RequireApprovalWhen != nil {
		in, out := &in.RequireApprovalWhen, &out.RequireApprovalWhen
		*out = make([]ApprovalTrigger, len(*in))
		copy(*out, *in)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]NotificationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ApprovalTimeout = in.ApprovalTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalConfig.
func (in *ApprovalConfig) DeepCopy() *ApprovalConfig {
	if in == nil {
		return nil
	}
	out := new(ApprovalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalTrigger) DeepCopyInto(out *ApprovalTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalTrigger.
func (in *ApprovalTrigger) DeepCopy() *ApprovalTrigger {
	if in == nil {
		return nil
	}
	out := new(ApprovalTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRollbackConfig) DeepCopyInto(out *AutoRollbackConfig) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRollbackConfig.
func (in *AutoRollbackConfig) DeepCopy() *AutoRollbackConfig {
	if in == nil {
		return nil
	}
	out := new(AutoRollbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerConfig) DeepCopyInto(out *CircuitBreakerConfig) {
	*out = *in
	out.ResetAfter = in.ResetAfter
	if in.TripConditions != nil {
		in, out := &in.TripConditions, &out.TripConditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerConfig.
func (in *CircuitBreakerConfig) DeepCopy() *CircuitBreakerConfig {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerVerticalConfig) DeepCopyInto(out *ContainerVerticalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerVerticalConfig.
func (in *ContainerVerticalConfig) DeepCopy() *ContainerVerticalConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerVerticalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoscaleRef) DeepCopyInto(out *CoscaleRef) {
	*out = *in
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoscaleRef.
func (in *CoscaleRef) DeepCopy() *CoscaleRef {
	if in == nil {
		return nil
	}
	out := new(CoscaleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostConfig) DeepCopyInto(out *CostConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostConfig.
func (in *CostConfig) DeepCopy() *CostConfig {
	if in == nil {
		return nil
	}
	out := new(CostConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostConstraints) DeepCopyInto(out *CostConstraints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostConstraints.
func (in *CostConstraints) DeepCopy() *CostConstraints {
	if in == nil {
		return nil
	}
	out := new(CostConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostStatus) DeepCopyInto(out *CostStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostStatus.
func (in *CostStatus) DeepCopy() *CostStatus {
	if in == nil {
		return nil
	}
	out := new(CostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyConfig) DeepCopyInto(out *DependencyConfig) {
	*out = *in
	if in.UpstreamOf != nil {
		in, out := &in.UpstreamOf, &out.UpstreamOf
		*out = make([]TargetRef, len(*in))
		copy(*out, *in)
	}
	if in.DownstreamOf != nil {
		in, out := &in.DownstreamOf, &out.DownstreamOf
		*out = make([]TargetRef, len(*in))
		copy(*out, *in)
	}
	if in.CoscalesWith != nil {
		in, out := &in.CoscalesWith, &out.CoscalesWith
		*out = make([]CoscaleRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyConfig.
func (in *DependencyConfig) DeepCopy() *DependencyConfig {
	if in == nil {
		return nil
	}
	out := new(DependencyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectionPolicy) DeepCopyInto(out *DirectionPolicy) {
	*out = *in
	out.Cooldown = in.Cooldown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectionPolicy.
func (in *DirectionPolicy) DeepCopy() *DirectionPolicy {
	if in == nil {
		return nil
	}
	out := new(DirectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedbackConfig) DeepCopyInto(out *FeedbackConfig) {
	*out = *in
	out.EvaluationDelay = in.EvaluationDelay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedbackConfig.
func (in *FeedbackConfig) DeepCopy() *FeedbackConfig {
	if in == nil {
		return nil
	}
	out := new(FeedbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedbackStatus) DeepCopyInto(out *FeedbackStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedbackStatus.
func (in *FeedbackStatus) DeepCopy() *FeedbackStatus {
	if in == nil {
		return nil
	}
	out := new(FeedbackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KEDAIntegration) DeepCopyInto(out *KEDAIntegration) {
	*out = *in
	out.ScaledObjectRef = in.ScaledObjectRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KEDAIntegration.
func (in *KEDAIntegration) DeepCopy() *KEDAIntegration {
	if in == nil {
		return nil
	}
	out := new(KEDAIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMConfig) DeepCopyInto(out *LLMConfig) {
	*out = *in
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(LLMProvider)
		**out = **in
	}
	if in.APIKeySecret != nil {
		in, out := &in.APIKeySecret, &out.APIKeySecret
		*out = new(SecretRef)
		**out = **in
	}
	out.CacheTTL = in.CacheTTL
	out.CircuitBreakerTimeout = in.CircuitBreakerTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMConfig.
func (in *LLMConfig) DeepCopy() *LLMConfig {
	if in == nil {
		return nil
	}
	out := new(LLMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMRateLimit) DeepCopyInto(out *LLMRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMRateLimit.
func (in *LLMRateLimit) DeepCopy() *LLMRateLimit {
	if in == nil {
		return nil
	}
	out := new(LLMRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMTelemetry) DeepCopyInto(out *LLMTelemetry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMTelemetry.
func (in *LLMTelemetry) DeepCopy() *LLMTelemetry {
	if in == nil {
		return nil
	}
	out := new(LLMTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationChannel) DeepCopyInto(out *NotificationChannel) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationChannel.
func (in *NotificationChannel) DeepCopy() *NotificationChannel {
	if in == nil {
		return nil
	}
	out := new(NotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrecedenceConfig) DeepCopyInto(out *PrecedenceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrecedenceConfig.
func (in *PrecedenceConfig) DeepCopy() *PrecedenceConfig {
	if in == nil {
		return nil
	}
	out := new(PrecedenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrecedenceConflict) DeepCopyInto(out *PrecedenceConflict) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrecedenceConflict.
func (in *PrecedenceConflict) DeepCopy() *PrecedenceConflict {
	if in == nil {
		return nil
	}
	out := new(PrecedenceConflict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrecedenceStatus) DeepCopyInto(out *PrecedenceStatus) {
	*out = *in
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]PrecedenceConflict, len(*in))
		copy(*out, *in)
	}
	if in.ActiveOverrides != nil {
		in, out := &in.ActiveOverrides, &out.ActiveOverrides
		*out = make([]ActiveOverride, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrecedenceStatus.
func (in *PrecedenceStatus) DeepCopy() *PrecedenceStatus {
	if in == nil {
		return nil
	}
	out := new(PrecedenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionStatus) DeepCopyInto(out *PredictionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionStatus.
func (in *PredictionStatus) DeepCopy() *PredictionStatus {
	if in == nil {
		return nil
	}
	out := new(PredictionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveEvent) DeepCopyInto(out *PredictiveEvent) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveEvent.
func (in *PredictiveEvent) DeepCopy() *PredictiveEvent {
	if in == nil {
		return nil
	}
	out := new(PredictiveEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingConfig) DeepCopyInto(out *PredictiveScalingConfig) {
	*out = *in
	out.LookaheadWindow = in.LookaheadWindow
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]PredictiveEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingConfig.
func (in *PredictiveScalingConfig) DeepCopy() *PredictiveScalingConfig {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposedAction) DeepCopyInto(out *ProposedAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposedAction.
func (in *ProposedAction) DeepCopy() *ProposedAction {
	if in == nil {
		return nil
	}
	out := new(ProposedAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendedResources) DeepCopyInto(out *RecommendedResources) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
	out.CPULimit = in.CPULimit.DeepCopy()
	out.MemoryLimit = in.MemoryLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendedResources.
func (in *RecommendedResources) DeepCopy() *RecommendedResources {
	if in == nil {
		return nil
	}
	out := new(RecommendedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceProfile) DeepCopyInto(out *ResourceProfile) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceProfile.
func (in *ResourceProfile) DeepCopy() *ResourceProfile {
	if in == nil {
		return nil
	}
	out := new(ResourceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRecommendation) DeepCopyInto(out *ResourceRecommendation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRecommendation.
func (in *ResourceRecommendation) DeepCopy() *ResourceRecommendation {
	if in == nil {
		return nil
	}
	out := new(ResourceRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceRecommendation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRecommendationList) DeepCopyInto(out *ResourceRecommendationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRecommendationList.
func (in *ResourceRecommendationList) DeepCopy() *ResourceRecommendationList {
	if in == nil {
		return nil
	}
	out := new(ResourceRecommendationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceRecommendationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRecommendationSpec) DeepCopyInto(out *ResourceRecommendationSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.Analysis = in.Analysis
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRecommendationSpec.
func (in *ResourceRecommendationSpec) DeepCopy() *ResourceRecommendationSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceRecommendationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRecommendationStatus) DeepCopyInto(out *ResourceRecommendationStatus) {
	*out = *in
	if in.RecommendedResources != nil {
		in, out := &in.RecommendedResources, &out.RecommendedResources
		*out = new(RecommendedResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(UsagePercentiles)
		**out = **in
	}
	if in.LastAnalyzedAt != nil {
		in, out := &in.LastAnalyzedAt, &out.LastAnalyzedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRecommendationStatus.
func (in *ResourceRecommendationStatus) DeepCopy() *ResourceRecommendationStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceRecommendationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSet) DeepCopyInto(out *ResourceSet) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSet.
func (in *ResourceSet) DeepCopy() *ResourceSet {
	if in == nil {
		return nil
	}
	out := new(ResourceSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
	out.CPULimit = in.CPULimit.DeepCopy()
	out.MemoryLimit = in.MemoryLimit.DeepCopy()
	if in.LastResizeTime != nil {
		in, out := &in.LastResizeTime, &out.LastResizeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLO) DeepCopyInto(out *SLO) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLO.
func (in *SLO) DeepCopy() *SLO {
	if in == nil {
		return nil
	}
	out := new(SLO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOViolationBudget) DeepCopyInto(out *SLOViolationBudget) {
	*out = *in
	out.Window = in.Window
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOViolationBudget.
func (in *SLOViolationBudget) DeepCopy() *SLOViolationBudget {
	if in == nil {
		return nil
	}
	out := new(SLOViolationBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyConfig) DeepCopyInto(out *SafetyConfig) {
	*out = *in
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(DirectionPolicy)
		**out = **in
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(DirectionPolicy)
		**out = **in
	}
	if in.CircuitBreaker != nil {
		in, out := &in.CircuitBreaker, &out.CircuitBreaker
		*out = new(CircuitBreakerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoRollback != nil {
		in, out := &in.AutoRollback, &out.AutoRollback
		*out = new(AutoRollbackConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyConfig.
func (in *SafetyConfig) DeepCopy() *SafetyConfig {
	if in == nil {
		return nil
	}
	out := new(SafetyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingApproval) DeepCopyInto(out *ScalingApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingApproval.
func (in *ScalingApproval) DeepCopy() *ScalingApproval {
	if in == nil {
		return nil
	}
	out := new(ScalingApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingApproval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingApprovalList) DeepCopyInto(out *ScalingApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingApprovalList.
func (in *ScalingApprovalList) DeepCopy() *ScalingApprovalList {
	if in == nil {
		return nil
	}
	out := new(ScalingApprovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingApprovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingApprovalSpec) DeepCopyInto(out *ScalingApprovalSpec) {
	*out = *in
	out.AIScalerRef = in.AIScalerRef
	out.ProposedAction = in.ProposedAction
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingApprovalSpec.
func (in *ScalingApprovalSpec) DeepCopy() *ScalingApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingApprovalStatus) DeepCopyInto(out *ScalingApprovalStatus) {
	*out = *in
	if in.ApprovedAt != nil {
		in, out := &in.ApprovedAt, &out.ApprovedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingApprovalStatus.
func (in *ScalingApprovalStatus) DeepCopy() *ScalingApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraints) DeepCopyInto(out *ScalingConstraints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraints.
func (in *ScalingConstraints) DeepCopy() *ScalingConstraints {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicy) DeepCopyInto(out *ScalingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicy.
func (in *ScalingPolicy) DeepCopy() *ScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicyDefaults) DeepCopyInto(out *ScalingPolicyDefaults) {
	*out = *in
	if in.Safety != nil {
		in, out := &in.Safety, &out.Safety
		*out = new(SafetyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CostConstraints != nil {
		in, out := &in.CostConstraints, &out.CostConstraints
		*out = new(CostConstraints)
		**out = **in
	}
	if in.SLOs != nil {
		in, out := &in.SLOs, &out.SLOs
		*out = make([]SLO, len(*in))
		copy(*out, *in)
	}
	if in.LLMRateLimit != nil {
		in, out := &in.LLMRateLimit, &out.LLMRateLimit
		*out = new(LLMRateLimit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicyDefaults.
func (in *ScalingPolicyDefaults) DeepCopy() *ScalingPolicyDefaults {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicyDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicyList) DeepCopyInto(out *ScalingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicyList.
func (in *ScalingPolicyList) DeepCopy() *ScalingPolicyList {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicySpec) DeepCopyInto(out *ScalingPolicySpec) {
	*out = *in
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicySpec.
func (in *ScalingPolicySpec) DeepCopy() *ScalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicyStatus) DeepCopyInto(out *ScalingPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicyStatus.
func (in *ScalingPolicyStatus) DeepCopy() *ScalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulePolicy) DeepCopyInto(out *SchedulePolicy) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetReplicas != nil {
		in, out := &in.TargetReplicas, &out.TargetReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulePolicy.
func (in *SchedulePolicy) DeepCopy() *SchedulePolicy {
	if in == nil {
		return nil
	}
	out := new(SchedulePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSpec) DeepCopyInto(out *ScheduleSpec) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSpec.
func (in *ScheduleSpec) DeepCopy() *ScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScaling) DeepCopyInto(out *ScheduledScaling) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScaling.
func (in *ScheduledScaling) DeepCopy() *ScheduledScaling {
	if in == nil {
		return nil
	}
	out := new(ScheduledScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledScaling) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingList) DeepCopyInto(out *ScheduledScalingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScheduledScaling, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingList.
func (in *ScheduledScalingList) DeepCopy() *ScheduledScalingList {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledScalingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingSpec) DeepCopyInto(out *ScheduledScalingSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.Schedule.DeepCopyInto(&out.Schedule)
	in.Policy.DeepCopyInto(&out.Policy)
	if in.TTLAfterCompletion != nil {
		in, out := &in.TTLAfterCompletion, &out.TTLAfterCompletion
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingSpec.
func (in *ScheduledScalingSpec) DeepCopy() *ScheduledScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingStatus) DeepCopyInto(out *ScheduledScalingStatus) {
	*out = *in
	if in.NextActivation != nil {
		in, out := &in.NextActivation, &out.NextActivation
		*out = (*in).DeepCopy()
	}
	if in.LastActivation != nil {
		in, out := &in.LastActivation, &out.LastActivation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingStatus.
func (in *ScheduledScalingStatus) DeepCopy() *ScheduledScalingStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalSourceConfig) DeepCopyInto(out *SignalSourceConfig) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalSourceConfig.
func (in *SignalSourceConfig) DeepCopy() *SignalSourceConfig {
	if in == nil {
		return nil
	}
	out := new(SignalSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetPolicy) DeepCopyInto(out *StatefulSetPolicy) {
	*out = *in
	out.DrainTimeout = in.DrainTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetPolicy.
func (in *StatefulSetPolicy) DeepCopy() *StatefulSetPolicy {
	if in == nil {
		return nil
	}
	out := new(StatefulSetPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePercentiles) DeepCopyInto(out *UsagePercentiles) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePercentiles.
func (in *UsagePercentiles) DeepCopy() *UsagePercentiles {
	if in == nil {
		return nil
	}
	out := new(UsagePercentiles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalConstraints) DeepCopyInto(out *VerticalConstraints) {
	*out = *in
	out.MinCPURequest = in.MinCPURequest.DeepCopy()
	out.MaxCPURequest = in.MaxCPURequest.DeepCopy()
	out.MinMemoryRequest = in.MinMemoryRequest.DeepCopy()
	out.MaxMemoryRequest = in.MaxMemoryRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalConstraints.
func (in *VerticalConstraints) DeepCopy() *VerticalConstraints {
	if in == nil {
		return nil
	}
	out := new(VerticalConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalDecision) DeepCopyInto(out *VerticalDecision) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
	out.CPULimit = in.CPULimit.DeepCopy()
	out.MemoryLimit = in.MemoryLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalDecision.
func (in *VerticalDecision) DeepCopy() *VerticalDecision {
	if in == nil {
		return nil
	}
	out := new(VerticalDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalScalingConfig) DeepCopyInto(out *VerticalScalingConfig) {
	*out = *in
	in.Constraints.DeepCopyInto(&out.Constraints)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerVerticalConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalScalingConfig.
func (in *VerticalScalingConfig) DeepCopy() *VerticalScalingConfig {
	if in == nil {
		return nil
	}
	out := new(VerticalScalingConfig)
	in.DeepCopyInto(out)
	return out
}
