apiVersion: aiscaler.io/v1
kind: AIScaler
metadata:
  name: nginx-test-scaler
spec:
  targetRef:
    name: nginx-test
    namespace: default

  constraints:
    minReplicas: 1
    maxReplicas: 5
    maxScaleStep: 2

  llm:
    primary: ollama
    model: qwen3:8b-q4_K_M

  prometheus:
    baseURL: "http://localhost:9090"

  evaluationInterval: 30s
  cooldownPeriod: 60s
  dryRun: false